# OpenStackClientDemo
OpenStack Instance Auto Mount Volume

# Run
./instance_auto_mount_volume.py

# Output
stack@jeremy-desktop:~$ ./test.py 
All clean everthing....
The instance test1 will be deleted!
The flavor 2U2G20 has been deleted!
The image Test Image has been deleted!
The cloud_pub_key have been deleted!
Floating ip 172.24.4.4 has been deleted!
Waiting for the instance to be deleted!
Waiting for the instance to be deleted!
Waiting for the instance to be deleted!
The instance has been deleted!
The volume test-vol has been deleted successfully!
The cloud_pub_key has been created!
The flavor 2U2G20 has been created!
The image trusty-server-cloudimg-amd64-disk1.img has been uploaded!
The instance 3e6382b7-c217-4f12-85cc-0cb7fa07ff5b has been created!
The volume test-vol has been created!
The current state of the instance is BUILD
The current state of the instance is BUILD
The current state of the instance is BUILD
The current state of the instance is BUILD
The current state of the instance is BUILD
The current state of the instance is BUILD
The current state of the instance is BUILD
The current state of the instance is BUILD
The current state of the instance is BUILD
The current state of the instance is BUILD
The current state of the instance is BUILD
The current state of the instance is BUILD
The current state of the instance is BUILD
The current state of the instance is BUILD
The current state of the instance is BUILD
The current state of the instance is BUILD
The current state of the instance is BUILD
The current state of the instance is OK!
The 172.24.4.4 has been allocated to the instance!
The current state of the volume is OK!
The volume test-vol has mount to instance test1!
The current state of the volume mount is attaching!
The current state of the volume mount is attaching!
The current state of the volume mount is attaching!
The current state of the volume mount is attaching!
The volume has been mounted!
Connection Failed because [Errno 111] Connection refused!!!!
Connection Failed because [Errno 111] Connection refused!!!!
Connection Failed because [Errno 111] Connection refused!!!!
Connection Failed because [Errno 111] Connection refused!!!!
Connection Failed because [Errno 111] Connection refused!!!!
Connection Failed because [Errno 111] Connection refused!!!!
Connection Failed because [Errno 111] Connection refused!!!!
Connection Failed because [Errno 111] Connection refused!!!!
Connection Failed because [Errno 111] Connection refused!!!!
Connection Failed because [Errno 111] Connection refused!!!!
Connection Failed because [Errno 111] Connection refused!!!!
Connection Failed because [Errno 111] Connection refused!!!!
Connecting Successfully!
Filesystem label=
OS type: Linux
Block size=4096 (log=2)
Fragment size=4096 (log=2)
Stride=0 blocks, Stripe width=0 blocks
131072 inodes, 524288 blocks
26214 blocks (5.00%) reserved for the super user
First data block=0
Maximum filesystem blocks=536870912
16 block groups
32768 blocks per group, 32768 fragments per group
8192 inodes per group
Superblock backups stored on blocks:
    32768, 98304, 163840, 229376, 294912

Allocating group tables: done
Writing inode tables: done
Creating journal (16384 blocks): done
Writing superblocks and filesystem accounting information: done
